{"name": "test_2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3", "trace": "@pytest.mark.sanity\n    def test_2():\n>       assert 2 == 3\nE       assert 2 == 3\n\ntests\\test_index_page.py:29: AssertionError"}, "start": 1665519806786, "stop": 1665519806786, "uuid": "1b42effb-5e7d-4fbf-9e62-ed9e74b8be62", "historyId": "4c4097db74f16f6dc35353eda320a6de", "testCaseId": "835c1059d1b211112e55e496e9c003e7", "fullName": "tests.test_index_page#test_2", "labels": [{"name": "tag", "value": "sanity"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_index_page"}, {"name": "host", "value": "BSI-US-GN72JR3"}, {"name": "thread", "value": "3712-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_index_page"}]}